print("=====================Cadastro de clientes vers 1.0===================")
print()
nome = str(input("Informe seu nome :"))
idade = int(input("Informe sua idade :"))
nascimento = int(input("Informe seu ano de nascimento :"))
cpf = int(input("Informe seu cpf :"))
print("confira as informações.")
print()
print("nome :",nome)
print("idade :",idade)
print("nascimento:",nascimento)
print("cpf :",cpf)
print("Meu nome é %s, eu tenho %d anos, nasci em %d, e meu cpf é: %d" %(nome,idade,nascimento,cpf))

